USE customer_behaviour;

SHOW TABLES;

SELECT * FROM customer LIMIT 10;


#Q1: What is the total revenue generated by male vs. female customers? 

select gender,sum(purchase_amount) from customer group by gender;

#Q2: Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount from customer 
where discount_applied="yes" and purchase_amount>=(select avg(purchase_amount) from customer);



#Q3: Which are the top 5 products with the highest average review rating? 

select item_purchased,round(avg(review_rating),1) as "avg product rating" from customer
group by item_purchased
order by avg(review_rating)desc
limit 5; 

#Q4: Compare the average purchase amount between Standard and Express Shipping. 

select shipping_type,
round(avg(purchase_amount),2) from customer
where shipping_type in ("express","standard")
group by shipping_type;


#Q5: Do subscribed customers spend more? (Compare average spend and total revenue between subscribers and non-subscribers). 

select subscription_status,
count(customer_id),
avg(purchase_amount),sum(purchase_amount) from customer 
group by subscription_status;


#Q6: Which 5 products have the highest percentage of purchases with discounts applied? 

select item_purchased,
100*(sum(case when discount_applied="yes"  then 1 else 0 end))/count(*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


#Q7: Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

with customer_type as(
select customer_id,previous_purchases,
case
    when previous_purchases=1 then "new"
    when previous_purchases between 2 and 10 then "returning"
    else "loyal"
    end as customer_segment
from customer)
select customer_segment,count(*) as "customer type"from customer_type
 group by customer_segment
 order by count(customer_segment)asc; 


#Q8: What are the top 3 most purchased products within each category? 

with top_product as(
select item_purchased,
category,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc)  as ranked_items
from customer
group by category,item_purchased)

select category,item_purchased,total_orders,ranked_items
from top_product
where ranked_items<=3;




#Q9: Are customers who are repeat buyers also likely to subscribe? (Repeat buyers are defined as having more than 5 previous purchases). 

select count(customer_id) as count_of_customers,
subscription_status from customer
where previous_purchases>=5
group by subscription_status;

#Q10: What is the total revenue generated across different age groups? 

select age_group,sum(purchase_amount)
from customer
group by age_group
order by sum(purchase_amount)desc;
